Feature/prototype
VoyagerYoshida/python-design-patterns pull request #5
Opened 2021-08-30 07:05 UTC by nadamoto131

---
title: 'Prototype merge to main branch'

---

## チェック項目
### メインタスクへの対応
- [x] ソースコードの追加
- [x] README.md の整備
- [x] クラス図の非透過処理

close #4 issue

### 追加タスクへの対応
- [x] 今回は特に無し

2021-08-30 07:34 UTC, VoyagerYoshida requested changes
僕からは 2 点だけ. 
- README のタイトルの重複
- クラス定義の外部ファイル化
修正よろしくお願いします.

2021-08-30 07:34 UTC, VoyagerYoshida commented on create/Prototype/README.md
> +# Prototype
重複している.

2021-08-30 07:34 UTC, VoyagerYoshida commented on create/Prototype/src/main.py
> +class Point:
クラスの定義は外部ファイルに出す.

2021-08-30 07:34 UTC, VoyagerYoshida commented on create/Prototype/src/main_assignment.py
> +class Point:
main.py と同一のクラスを読み込む.

2021-08-30 08:05 UTC, nadamoto131 commented on create/Prototype/README.md
> +# Prototype
重複を修正しました.

2021-08-30 08:06 UTC, nadamoto131 commented on create/Prototype/src/main.py
> +class Point:
クラスの定義を外部ファイルに出し, 各 main ファイルで読み込む形式に修正しました.

2021-08-30 08:10 UTC, VoyagerYoshida commented on create/Prototype/README.md
> +# Prototype
確認しました.

2021-08-30 08:11 UTC, VoyagerYoshida commented on create/Prototype/src/main.py
> +class Point:
確認しました.

2021-08-30 08:24 UTC, VoyagerYoshida approved these changes

2021-09-28 09:08 UTC, potato-na commented
遅くなってごめんなさい. 
ok です

2021-09-28 15:34 UTC, VoyagerYoshida commented
@potato-na 
pending review を approval にしてもらえる？

2021-09-30 08:09 UTC, potato-na approved these changes

2021-09-30 09:02 UTC, merged